<?php 


    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE
    // NUNCA FAZER DELETE SEM WHERE


    // DELETE FROM itens WHERE id = 4;

?>